development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%=ENV['USER']%>
  database: lunchpicker

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%=ENV['USER']%>
  database: lunchpicker_test
